main: dev.aschim.mc.motdr.Main
name: MOTDr
description: Display random MOTDs on every ping, and when players join the server
version: 0.1
api-version: 1.18
author: 727021
# TODO: Permissions
# TODO: Commands